### ISSUE TITLE
Separate events and queries in `QueryService`

### ISSUE THREAD

**Issue by albamig** [Clariteia/minos_microservice_cqrs#19]
Currently, we mix both `@enroute.{}.query` and `@enroute.{}.event` within the `QueryService` classes. This works nice when the query service own a small number of queries and reacts to a small number of events. When those get bigger, the class size starts to increase a lot.

I propose to separate event handlers and queries in different files but still within the `queries` folder and `QueryService` namespace.

**Comment by garciparedes** [comment]
Hi @albamig! According to the latest `minos-microservice-networks` release (https://github.com/Clariteia/minos_microservice_networks/releases/tag/v0.2.0) now it's possible to use any number of service classes, so with this new feature I think this issue is already satisfied (as now it is more a design strategy that must be followed by the microservice developer than a framework constraint)

**Comment by albamig** [comment]
That's great news @garciparedes! Maybe we can set an example in the `e-commerce` so people get to know the possibility?

I'll close the issue anyway.
